// Code generated by Thrift Compiler (0.15.0). DO NOT EDIT.

package linethrift

import (
	"../thrift"
	"bytes"
	"context"
	"fmt"
	"time"
)

// (needed to ensure safety because of naive import list construction.)
var _ = thrift.ZERO
var _ = fmt.Printf
var _ = context.Background
var _ = time.Now
var _ = bytes.Equal

func init() {
}
