// Code generated by Thrift Compiler (0.15.0). DO NOT EDIT.

package main

import (
	"context"
	"flag"
	"fmt"
	"math"
	"net"
	"net/url"
	"os"
	"strconv"
	"strings"
	"github.com/apache/thrift/lib/go/thrift"
	"linethrift"
)

var _ = linethrift.GoUnusedProtection__

func Usage() {
  fmt.Fprintln(os.Stderr, "Usage of ", os.Args[0], " [-h host:port] [-u url] [-f[ramed]] function [arg1 [arg2...]]:")
  flag.PrintDefaults()
  fmt.Fprintln(os.Stderr, "\nFunctions:")
  fmt.Fprintln(os.Stderr, "  OTPResult issueOTP(string channelId)")
  fmt.Fprintln(os.Stderr, "  ChannelToken approveChannelAndIssueChannelToken(string channelId)")
  fmt.Fprintln(os.Stderr, "  string approveChannelAndIssueRequestToken(string channelId, string otpId)")
  fmt.Fprintln(os.Stderr, "  NotificationFetchResult fetchNotificationItems(i64 localRev)")
  fmt.Fprintln(os.Stderr, "  ApprovedChannelInfos getApprovedChannels(i64 lastSynced, string locale)")
  fmt.Fprintln(os.Stderr, "  ChannelInfo getChannelInfo(string channelId, string locale)")
  fmt.Fprintln(os.Stderr, "  ChannelNotificationSetting getChannelNotificationSetting(string channelId, string locale)")
  fmt.Fprintln(os.Stderr, "   getChannelNotificationSettings(string locale)")
  fmt.Fprintln(os.Stderr, "  ChannelInfos getChannels(i64 lastSynced, string locale)")
  fmt.Fprintln(os.Stderr, "  ChannelDomains getDomains(i64 lastSynced)")
  fmt.Fprintln(os.Stderr, "  ChannelDomains getCommonDomains(i64 lastSynced)")
  fmt.Fprintln(os.Stderr, "  ChannelToken issueChannelToken(string channelId)")
  fmt.Fprintln(os.Stderr, "  string issueRequestToken(string channelId, string otpId)")
  fmt.Fprintln(os.Stderr, "  RequestTokenResponse issueRequestTokenWithAuthScheme(string channelId, string otpId,  authScheme, string returnUrl)")
  fmt.Fprintln(os.Stderr, "  string issueRequestTokenForAutoLogin(string channelId, string otpId, string redirectUrl)")
  fmt.Fprintln(os.Stderr, "   getUpdatedChannelIds( channelIds)")
  fmt.Fprintln(os.Stderr, "  void revokeChannel(string channelId)")
  fmt.Fprintln(os.Stderr, "  ChannelSyncDatas syncChannelData(i64 lastSynced, string locale)")
  fmt.Fprintln(os.Stderr)
  os.Exit(0)
}

type httpHeaders map[string]string

func (h httpHeaders) String() string {
  var m map[string]string = h
  return fmt.Sprintf("%s", m)
}

func (h httpHeaders) Set(value string) error {
  parts := strings.Split(value, ": ")
  if len(parts) != 2 {
    return fmt.Errorf("header should be of format 'Key: Value'")
  }
  h[parts[0]] = parts[1]
  return nil
}

func main() {
  flag.Usage = Usage
  var host string
  var port int
  var protocol string
  var urlString string
  var framed bool
  var useHttp bool
  headers := make(httpHeaders)
  var parsedUrl *url.URL
  var trans thrift.TTransport
  _ = strconv.Atoi
  _ = math.Abs
  flag.Usage = Usage
  flag.StringVar(&host, "h", "localhost", "Specify host and port")
  flag.IntVar(&port, "p", 9090, "Specify port")
  flag.StringVar(&protocol, "P", "binary", "Specify the protocol (binary, compact, simplejson, json)")
  flag.StringVar(&urlString, "u", "", "Specify the url")
  flag.BoolVar(&framed, "framed", false, "Use framed transport")
  flag.BoolVar(&useHttp, "http", false, "Use http")
  flag.Var(headers, "H", "Headers to set on the http(s) request (e.g. -H \"Key: Value\")")
  flag.Parse()
  
  if len(urlString) > 0 {
    var err error
    parsedUrl, err = url.Parse(urlString)
    if err != nil {
      fmt.Fprintln(os.Stderr, "Error parsing URL: ", err)
      flag.Usage()
    }
    host = parsedUrl.Host
    useHttp = len(parsedUrl.Scheme) <= 0 || parsedUrl.Scheme == "http" || parsedUrl.Scheme == "https"
  } else if useHttp {
    _, err := url.Parse(fmt.Sprint("http://", host, ":", port))
    if err != nil {
      fmt.Fprintln(os.Stderr, "Error parsing URL: ", err)
      flag.Usage()
    }
  }
  
  cmd := flag.Arg(0)
  var err error
  if useHttp {
    trans, err = thrift.NewTHttpClient(parsedUrl.String())
    if len(headers) > 0 {
      httptrans := trans.(*thrift.THttpClient)
      for key, value := range headers {
        httptrans.SetHeader(key, value)
      }
    }
  } else {
    portStr := fmt.Sprint(port)
    if strings.Contains(host, ":") {
           host, portStr, err = net.SplitHostPort(host)
           if err != nil {
                   fmt.Fprintln(os.Stderr, "error with host:", err)
                   os.Exit(1)
           }
    }
    trans, err = thrift.NewTSocket(net.JoinHostPort(host, portStr))
    if err != nil {
      fmt.Fprintln(os.Stderr, "error resolving address:", err)
      os.Exit(1)
    }
    if framed {
      trans = thrift.NewTFramedTransport(trans)
    }
  }
  if err != nil {
    fmt.Fprintln(os.Stderr, "Error creating transport", err)
    os.Exit(1)
  }
  defer trans.Close()
  var protocolFactory thrift.TProtocolFactory
  switch protocol {
  case "compact":
    protocolFactory = thrift.NewTCompactProtocolFactory()
    break
  case "simplejson":
    protocolFactory = thrift.NewTSimpleJSONProtocolFactory()
    break
  case "json":
    protocolFactory = thrift.NewTJSONProtocolFactory()
    break
  case "binary", "":
    protocolFactory = thrift.NewTBinaryProtocolFactoryDefault()
    break
  default:
    fmt.Fprintln(os.Stderr, "Invalid protocol specified: ", protocol)
    Usage()
    os.Exit(1)
  }
  iprot := protocolFactory.GetProtocol(trans)
  oprot := protocolFactory.GetProtocol(trans)
  client := linethrift.NewChannelServiceClient(thrift.NewTStandardClient(iprot, oprot))
  if err := trans.Open(); err != nil {
    fmt.Fprintln(os.Stderr, "Error opening socket to ", host, ":", port, " ", err)
    os.Exit(1)
  }
  
  switch cmd {
  case "issueOTP":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "IssueOTP requires 1 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := argvalue0
    fmt.Print(client.IssueOTP(context.Background(), value0))
    fmt.Print("\n")
    break
  case "approveChannelAndIssueChannelToken":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "ApproveChannelAndIssueChannelToken requires 1 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := argvalue0
    fmt.Print(client.ApproveChannelAndIssueChannelToken(context.Background(), value0))
    fmt.Print("\n")
    break
  case "approveChannelAndIssueRequestToken":
    if flag.NArg() - 1 != 2 {
      fmt.Fprintln(os.Stderr, "ApproveChannelAndIssueRequestToken requires 2 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := argvalue0
    argvalue1 := flag.Arg(2)
    value1 := argvalue1
    fmt.Print(client.ApproveChannelAndIssueRequestToken(context.Background(), value0, value1))
    fmt.Print("\n")
    break
  case "fetchNotificationItems":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "FetchNotificationItems requires 1 args")
      flag.Usage()
    }
    argvalue0, err1221 := (strconv.ParseInt(flag.Arg(1), 10, 64))
    if err1221 != nil {
      Usage()
      return
    }
    value0 := argvalue0
    fmt.Print(client.FetchNotificationItems(context.Background(), value0))
    fmt.Print("\n")
    break
  case "getApprovedChannels":
    if flag.NArg() - 1 != 2 {
      fmt.Fprintln(os.Stderr, "GetApprovedChannels requires 2 args")
      flag.Usage()
    }
    argvalue0, err1222 := (strconv.ParseInt(flag.Arg(1), 10, 64))
    if err1222 != nil {
      Usage()
      return
    }
    value0 := argvalue0
    argvalue1 := flag.Arg(2)
    value1 := argvalue1
    fmt.Print(client.GetApprovedChannels(context.Background(), value0, value1))
    fmt.Print("\n")
    break
  case "getChannelInfo":
    if flag.NArg() - 1 != 2 {
      fmt.Fprintln(os.Stderr, "GetChannelInfo requires 2 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := argvalue0
    argvalue1 := flag.Arg(2)
    value1 := argvalue1
    fmt.Print(client.GetChannelInfo(context.Background(), value0, value1))
    fmt.Print("\n")
    break
  case "getChannelNotificationSetting":
    if flag.NArg() - 1 != 2 {
      fmt.Fprintln(os.Stderr, "GetChannelNotificationSetting requires 2 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := argvalue0
    argvalue1 := flag.Arg(2)
    value1 := argvalue1
    fmt.Print(client.GetChannelNotificationSetting(context.Background(), value0, value1))
    fmt.Print("\n")
    break
  case "getChannelNotificationSettings":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "GetChannelNotificationSettings requires 1 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := argvalue0
    fmt.Print(client.GetChannelNotificationSettings(context.Background(), value0))
    fmt.Print("\n")
    break
  case "getChannels":
    if flag.NArg() - 1 != 2 {
      fmt.Fprintln(os.Stderr, "GetChannels requires 2 args")
      flag.Usage()
    }
    argvalue0, err1229 := (strconv.ParseInt(flag.Arg(1), 10, 64))
    if err1229 != nil {
      Usage()
      return
    }
    value0 := argvalue0
    argvalue1 := flag.Arg(2)
    value1 := argvalue1
    fmt.Print(client.GetChannels(context.Background(), value0, value1))
    fmt.Print("\n")
    break
  case "getDomains":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "GetDomains requires 1 args")
      flag.Usage()
    }
    argvalue0, err1231 := (strconv.ParseInt(flag.Arg(1), 10, 64))
    if err1231 != nil {
      Usage()
      return
    }
    value0 := argvalue0
    fmt.Print(client.GetDomains(context.Background(), value0))
    fmt.Print("\n")
    break
  case "getCommonDomains":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "GetCommonDomains requires 1 args")
      flag.Usage()
    }
    argvalue0, err1232 := (strconv.ParseInt(flag.Arg(1), 10, 64))
    if err1232 != nil {
      Usage()
      return
    }
    value0 := argvalue0
    fmt.Print(client.GetCommonDomains(context.Background(), value0))
    fmt.Print("\n")
    break
  case "issueChannelToken":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "IssueChannelToken requires 1 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := argvalue0
    fmt.Print(client.IssueChannelToken(context.Background(), value0))
    fmt.Print("\n")
    break
  case "issueRequestToken":
    if flag.NArg() - 1 != 2 {
      fmt.Fprintln(os.Stderr, "IssueRequestToken requires 2 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := argvalue0
    argvalue1 := flag.Arg(2)
    value1 := argvalue1
    fmt.Print(client.IssueRequestToken(context.Background(), value0, value1))
    fmt.Print("\n")
    break
  case "issueRequestTokenWithAuthScheme":
    if flag.NArg() - 1 != 4 {
      fmt.Fprintln(os.Stderr, "IssueRequestTokenWithAuthScheme requires 4 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := argvalue0
    argvalue1 := flag.Arg(2)
    value1 := argvalue1
    arg1238 := flag.Arg(3)
    mbTrans1239 := thrift.NewTMemoryBufferLen(len(arg1238))
    defer mbTrans1239.Close()
    _, err1240 := mbTrans1239.WriteString(arg1238)
    if err1240 != nil { 
      Usage()
      return
    }
    factory1241 := thrift.NewTJSONProtocolFactory()
    jsProt1242 := factory1241.GetProtocol(mbTrans1239)
    containerStruct2 := linethrift.NewChannelServiceIssueRequestTokenWithAuthSchemeArgs()
    err1243 := containerStruct2.ReadField3(context.Background(), jsProt1242)
    if err1243 != nil {
      Usage()
      return
    }
    argvalue2 := containerStruct2.AuthScheme
    value2 := argvalue2
    argvalue3 := flag.Arg(4)
    value3 := argvalue3
    fmt.Print(client.IssueRequestTokenWithAuthScheme(context.Background(), value0, value1, value2, value3))
    fmt.Print("\n")
    break
  case "issueRequestTokenForAutoLogin":
    if flag.NArg() - 1 != 3 {
      fmt.Fprintln(os.Stderr, "IssueRequestTokenForAutoLogin requires 3 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := argvalue0
    argvalue1 := flag.Arg(2)
    value1 := argvalue1
    argvalue2 := flag.Arg(3)
    value2 := argvalue2
    fmt.Print(client.IssueRequestTokenForAutoLogin(context.Background(), value0, value1, value2))
    fmt.Print("\n")
    break
  case "getUpdatedChannelIds":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "GetUpdatedChannelIds requires 1 args")
      flag.Usage()
    }
    arg1248 := flag.Arg(1)
    mbTrans1249 := thrift.NewTMemoryBufferLen(len(arg1248))
    defer mbTrans1249.Close()
    _, err1250 := mbTrans1249.WriteString(arg1248)
    if err1250 != nil { 
      Usage()
      return
    }
    factory1251 := thrift.NewTJSONProtocolFactory()
    jsProt1252 := factory1251.GetProtocol(mbTrans1249)
    containerStruct0 := linethrift.NewChannelServiceGetUpdatedChannelIdsArgs()
    err1253 := containerStruct0.ReadField1(context.Background(), jsProt1252)
    if err1253 != nil {
      Usage()
      return
    }
    argvalue0 := containerStruct0.ChannelIds
    value0 := argvalue0
    fmt.Print(client.GetUpdatedChannelIds(context.Background(), value0))
    fmt.Print("\n")
    break
  case "revokeChannel":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "RevokeChannel requires 1 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := argvalue0
    fmt.Print(client.RevokeChannel(context.Background(), value0))
    fmt.Print("\n")
    break
  case "syncChannelData":
    if flag.NArg() - 1 != 2 {
      fmt.Fprintln(os.Stderr, "SyncChannelData requires 2 args")
      flag.Usage()
    }
    argvalue0, err1255 := (strconv.ParseInt(flag.Arg(1), 10, 64))
    if err1255 != nil {
      Usage()
      return
    }
    value0 := argvalue0
    argvalue1 := flag.Arg(2)
    value1 := argvalue1
    fmt.Print(client.SyncChannelData(context.Background(), value0, value1))
    fmt.Print("\n")
    break
  case "":
    Usage()
    break
  default:
    fmt.Fprintln(os.Stderr, "Invalid function ", cmd)
  }
}
